name: Rebuild Hexo
on: push
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.2.0
        with:
          ssh-private-key: ${{ secrets.HEXO_SERVER_PRIVATE_KEY }}
          ssh-host: ${{ secrets.HEXO_HOST }}
          ssh-port: 22 # optional
      - name: Rebuild Hexo
        env:
          HEXO_HOST: ${{ secrets.HEXO_HOST }}
        run: echo $(ssh -q -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile /dev/null'  root@$HEXO_HOST "sh /usr/local/soft/hexo/king-note-web-starter.sh") | xargs sh
       
