name: Rebuild Hexo
on: push
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: fir
        run: sudo apt-get install ssh ;eval "$(ssh-agent -s)"; echo "${{secrets.HEXO_SERVER_PRIVATE_KEY}}" > ./id_rsa ;chmod 400 ./id_rsa; ssh-add ./id_rsa;cat "StrictHostKeyChecking no" > /etc/ssh/ssh_config.d/key_check.conf
      - name: rebuild-hexo
        run: ssh  root@121.41.104.162 "sh /usr/local/soft/hexo/king-note-web-starter.sh"


      # - name: SSHPASS Github Action
      #   # You may pin to the exact commit or the version.
      #   # uses: matheusvanzan/sshpass-action@1e96f05518c2e99d17587ee85fa4d64c1612d0f1
      #   uses: matheusvanzan/sshpass-action@v1
      #   with:
      #     # SSHPASS host
      #     host: 121.41.104.162
      #     # SSHPASS username
      #     username: root
      #     # SSHPASS password
      #     password:  ${{secrets.HEXO_SERVER_PASSWORD}} 
      #     # SSHPASS commands to run
      #     run: sh /usr/local/soft/hexo/king-note-web-starter.sh
